lib/strd_web/router.ex
defmodule StrdWeb.Router do
  use StrdWeb, :router

  import StrdWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StrdWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StrdWeb do
    pipe_through :browser

    get "/", LinkController, :index
    post "/", LinkController, :create
    get "/links/:short_url", LinkController, :show

    if Mix.env() in [:dev, :test] do
      import Phoenix.LiveDashboard.Router
      live_dashboard "/dashboard", metrics: StrdWeb.Telemetry
    end

    get "/:short_url", LinkController, :redirect_short_url
  end

  scope "/", StrdWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/my/links", LinkController, :mylinks_index
  end

  # Other scopes may use custom stacks.
  # scope "/api", StrdWeb do
  #   pipe_through :api
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", StrdWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", StrdWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", StrdWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/strd_web/views/layout_view.ex
defmodule StrdWeb.LayoutView do
  use StrdWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/strd_web/templates/layout/_user_menu.html.heex
<nav class="user-menu" x-data="{ isOpen: false}">

    <div
      href="#"
      class="user-profile"
      @click="isOpen = !isOpen"
      @keydown.escape="isOpen = false"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#354BEB" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
        <circle cx="12" cy="7" r="4"></circle>
      </svg>
    </div>
    <ul x-show="isOpen" @click.away="isOpen = false" class="dropdown">
      <%= if @current_user do %>
        <li class="email"><%= @current_user.email %></li>
        <li><%= link to: Routes.link_path(@conn, :mylinks_index) do %>Your Links<% end %></li>
        <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
        <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
      <% else %>
        <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
        <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
      <% end %>

      <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
      <% end %>
    </ul>

</nav>

lib/strd_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/strd_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/strd_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Strd" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script src="//unpkg.com/alpinejs" defer></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <%= link to: Routes.link_path(@conn, :index), class: "navbar-home" do %>
            <img src={Routes.static_path(@conn, "/images/logo.png")} alt="Stord Logo" />
          <% end %>
        </nav>
        <h1>strd.</h1>
        <%= render "_user_menu.html", assigns %>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>